# 에러 처리

> 안정성 지원은 에러 처리까지 이어진다. 러스트는 에러 처리에 대한 다양한 기능을 제공한다.
> 에러의 발생 가능성을 인지하고 개발자가 코드를 컴파일하기 전에 에러를 처리하도록 유도한다.
> 운영 환경에 배포하기 전에 적절하게 에러를 찾아 처리하도록 보장한다.

러스트는 에러를 크게 2가지로 나눈다

- 회복 가능한 (Recoverable)
  - ex) 존재하지 않는 파일 접근
  - 사용자에게 문제를 보고하고 작업을 다시 시도할 수 있다
  - `Result<T, E>` 타입 제공
- 회복 불가능한 (Unrecoverable)
  - ex) 배열의 범위를 벗어나는 메모리에 대한 접근
  - 버그의 가능성을 내포한다
  - 회복 불가능한 에러 발생 시 프로그램 실행 종료하는 `panic!` 매크로 제공

- 대다수의 언어는 두 가지를 구분하지 않고 예외(Exception) 매커니즘으로 처리한다.
- 러스트에는 예외가 없음

## panic! 매크로를 이용한 회복 불가능한 에러 처리

- 코드에 문제가 생겼는데 처리할 방법이 전혀 없는 경우 사용
- `panic!` 매크로를 실행하면 프로그램은 실패 메시지를 출력, 스택 정리 후 종료

> 스택을 풀지 않고 바로 삭제해야할때
>
> 프로그램에 패닉이 발생하면 스택을 풀기 시작한다. 러스트는 스택을 역순으로 순회하면서 각 함수에 전달되었던 데이터를 정리한다.
> 하지만 프로그램이 클수록 많은 리소스가 존재하기 때문에 스택을 즉시 취소해서 운영체제에 맡기는 방법이 있다.
> - 프로그램의 바이너리 파일 크기를 최대한 작게 해야 한다면 Cargo.toml 파일의 [profile] 섹션에 panic = 'abort'를 추가해서 스택을 풀어주지 않고 취소하게 할 수 있다.

```rust
fn main() {
  panic!("crash and burn");
}
```

- 패닉 매크로를 호출하면 패닉 메시지와 패닉이 발생한 소스 코드 위치가 출력된다

### panic! 역추적 사용하기

- 라이브러리 안에서 `panic!` 매크로가 호출되는 경우

```rust
fn main() {
  let v = vec![1,2,3];
  v[99];
}
```

- C 같은 언어는 원치 않던 값이라도 개발자가 지정한 위치의 값을 리턴
  - 인덱스로 지정한 위치의 메모리가 벡터가 관리하는 메모리가 아니더라도 벡터에 저장된 값에 해당하는 위치의 메모리에 저장된 값 리턴
  - 이를 **버퍼 오버리드** 라고 함
  - 이렇게 되면 인덱스를 조작해서 읽어선 안될 값을 읽어버리는 문제가 발생, 보안상 취약

- 러스트는 이런 상황을 막기위해 이런 상황에서 패닉을 실행한다.
- 그렇기 때문에, 역 추적을 할 수 있도록 `RUST_BACKTRACE`를 제공하며, `RUST_BACKTRACE` 환경 변수에 1 이상 값을 설정하면 BACK_TRACE 갯수만큼 에러에서 알려준다.

## Result 타입으로 에러 처리하기

- 치명적인 에러도 있겠지만, 그렇지 않은 대부분의 에러도 있다.
- 대부분 함수 호출에 실패하면 쉽게 그 이유를 파악해서 대처할 수 있음

```rust
enum Result<T, E> {
  Ok(T),
  Err(E),
}
```

- T, E는 제네릭 타입 매개변수이다.
- T = 성공 할 경우 타입
- E = 실패 할 경우 타입

```rust
use std::fs::File;

fn main() {
  let f = File::open("hello.text");
}
```

- `File::open` 함수가 `Result<T,E>` 타입을 리턴한다.
- 성공 시 `std::fs::File`, 실패 시 `std::io::Error`을 반환한다.

```rust
use std::fs::File;

fn main() {
  let f = File::open("hello.text");

  let f = match f {
    Ok(file) => file,
    Err(error) => {
      panic!("파일 열기 실패: {:?}", error);
    }
  }
}
```

- Result 열거자와 열것값은 프랠류드에 인해 자동으로 임포트된 상태이므로 명시할 필요가 없음. (Ok, Err에 Result를 명시할 필요가)
- 에러 발생하면 panic! 으로 인해, 프로그램이 종료되고 에러가 출력된다.

### match 표현식으로 여러 종류의 에러 처리하기

```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
  let f = File::open("hello.txt");

  let f = match f {
    Ok(file) => file,
    Err(ref error) => match error.kind() {
      ErrorKind::NotFound => match File::create("hello.txt") {
        Ok(fc) => fc,
        Err(e) => panic!("파일을 생성하지 못했습니다: {:?}", e),
      },
      other_error => panic!("파일을 열지 못했습니다: {:?}", other_error),
    },
  };
}
```

- ErrorKind 로 여러 에러 종류를 처리할 수 있다.
- NotFound가 아닌 다른 에러의 경우 일괄적으로 처리할 수 있도록 "other_error"를 추가한다.

### 에러 발생 시 패닉을 발생하는 더 빠른 방법: unwrap과 expect

- `Result<T, E>` 타입은 다양한 작업을 처리하기 위한 여러가지 도움 메서드들을 제공함
- match 표현식을 단축할 수 있는 메서드 = `unwrap()`
- Err => panic 호출

```rust
use std::fs::File;

fn main() {
  let f = File::open("hello.txt").unwrap();
}
```

- `expect()` 메서드는 panic! 매크로에 에러 메시지를 전달할 수 있다.

```rust
use std::fs::File;

fn main() {
  let f = File::open("hello.txt").expect("파일을 열 수 없습니다.");
}
```

- unwrap은 에러 특정이 어렵다. 그러므로 expect를 쓰자.

### 에러 전파하기

- 함수안에서 처리하지 않고 호출하는 코드에 에러를 리턴해서 호출자가 에러를 처리하게 할 수 있음
- 이를 `에러 전파`라고 함.

```rust
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() => Result<String, io::Error> {
  let f = File::open("hello.txt");

  let mut f = match f {
    Ok(file) => file,
    Err(e) => return Err(e),
  };

  let mut s = String::new();

  match f.read_to_string(&mut s) {
    Ok(_) => Ok(s),
    Err(e) => Err(e),
  }
}
```

- 리턴 타입에 대한 타입 어노테이션을 지정했다.
- 성공하면 파일 값을 받고, 실패하면 에러 코드를 반환한다.
- 파일 가져오기든, 읽기든 둘 다 에러 처리를 일괄적으로 할 수 있다.

#### ? 연산자를 이용해 에러를 더 쉽게 전파하기

```rust
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() -> Result<String, io::Error> {
  let mut f = File::open("hello.txt")?;
  let mut s = String::new();
  f.read_to_string(?mut s)?;
  Ok(s)
}
```

- Result 값 뒤에 덧붙인 ? 연산자는 match 표현식과 비슷하게 동작함
- Result 값이 Ok면 Ok 열것값에 저장된 값이 리턴된다.
- Err면 return 키워드를 사용한 것처럼 전체 함수의 리턴값이 되어 호출자로 에러가 전파됨

- match 표현식과 ? 연산자 동작은 차이점이 있다. ? 연산자의 경우 에러값은 from 함수를 이용해 전달됨
- 표준 라이브러리의 From 트레이트에 선언되어 있음, 에러를 한 타입에서 다른 타입으로 변환함.
- 리턴 에러 타입으로 변환하는 from 함수를 구현하는 한, ? 연산자가 자동으로 수행함

- ? 연산자를 이용하면 축약을 획기적으로 할 수 있다.

```rust
use std::io;
use std::io::Read;
use std::fs::File;

fn read_username_from_file() => Result<String, io::Error> {
  let mut s = String::new();

  File::open("hello.txt")?.read_to_string(&mut s);
  
  Ok(s)
}
```

- 코드를 더 공학적으로 작성했음
- 위의 코드와 동일함

```rust
use std::io;
use std::fs;

fn read_username_from_file() => Result<String, io:Error> {
  fs::read_to_string("hello.txt")?;
}
```

- 리턴타입으로 퉁쳐버릴수도 있음

#### ? 연산자는 Result 타입을 리턴하는 함수에서만 사용할 수 있다

- ? 연산자는 Result 타입을 리턴할 때만 사용할 수 있음
- 다른곳에서 사용하면 에러 뿜뿜
- Result 타입을 리턴하지 않는 함수 안에서 Result 타입을 리턴하는 다른 함수를 호출할 때는 호출자에게 에러 전파할 가능성이 있는 ?보다 match 표현식, 혹은 Result 타입의 메서드 중 하나를 사용해서 처리해야함

- main 함수는 특별한 함수기 때문에 리턴할 수 있는 값의 타입 제한이 있음

```rust
use std::error::Error;
use std::fs::File;

fn main() => Result<(), Box<dyn Error>> {
  let f = File::open("hello.txt")?;

  Ok(())
}
```

- () 리턴으로 main 함수에서 성공시 조건을 넣을 수 있다.
- `Box<dyn Error>` 타입은 트레이트 객체 라고 부르는 타입이다.
  - 모든 종류의 에러를 의미한다.

## 패닉에 빠질 것인가? 말 것인가?

- 대부분의 경우에는 `Result<T, E>` 를 써라
- 하지만 패닉을 발생시켜야 하는 경우가 있다. 아래의 예제를 확인하라

### 예제, 프로토타입 코드, 그리고 테스트

- 예제같은 데에서는 unwrap 같은 메서드 호출 부분은 애플리케이션이 상황에 따라 처리해야 할 에러가 발생할 수도 있다는 것을 표현하는 것으로 이미 받아들여지고 있음
- unwrap, expect 메서드는 에러를 어떻게 처리할 것인지 결정에 앞서, 프로토타이핑 상황에 유용함
- 빠르게 unwrap, expect로 짠 다음에 로직을 교체하는 형태로 작업하기에 알맞음 (일단 패닉을 주고 시작한다)
- TDD 등에 적합할 듯

### 컴파일러보다 개발자가 더 많은 정보를 가진 경우

- Ok 값 반환이 확실하더라도, 컴파일러가 해당 로직을 이해할 수 없을 경우(machine Readable 하지 않을경우) unwrap를 함께 호출하자

```rust
use std::new::IpAddr;
let home: IpAddr = "127.0.0.1".parse().unwrap();
```

- 127.0.0.1 은 실패할 일이 없지만, 이 문자열이 언제나 실패하지 않을지는 컴파일러가 알 수 없다.
- 그렇기에 Result 값이 Err인 경우를 처리하도록 강요한다.
- 혹시나 바뀌면 안되니까 unwrap() 해두라

### 에러 처리를 위한 조언

- 잘못된 상태: 어떤 가설, 보장, 계약, 불변 등이 깨진상황
  - 유효하지 않은 값, 모순된 값, 실수로 놓친 값이 코드로 전달되는 상황
    - 잘못된 상태는 원래 기대했던 동작이 어쩌다 실패하는 상황을 말하는게 아님
    - 어느 지점 이후의 코드는 프로그램이 절대 잘못된 상태에 놓이지 않아야만 정상적으로 동작
    - 이 정보를 사용중인 타입으로 표현할 방법이 없음

- 적절하지 않은 값을 전달했다면 가장 좋은 선택은 panic! 매크로를 호출해서 라이브러리 사용하는 개발자 코드에 버그 있음을 알려줘야 함
  - 개발자가 직접 제어할 수 없는 외부 코드 호출 시 수정할 방법이 없으면 유효한 방법
  - 하지만 어떤 이유로 작업이 실패할 수 있다면 Result<T,E> 써라
    - 파서에 잘못된 형식의 데이터가 전달되거나 HTTP 요청을 보냈는데 그 요청이 호출 횟수 제한으로 인해 에러를 리턴하는 경우
    - 실패할 가능성이 있었음이 명확할 때, 에러 전파하여 호출자에게 처리할 수 있도록 위임한다.
- 작업 수행시 유효한지 검사하고 그렇지 않으면 패닉을 발생시켜라
  - 안정성: 유효하지 않은 데이터 기반으로 작업하면 코드 취약점 노출
    - 표준 라이브러리가 유효한 범위 벗어나는 데이터 메모리에 접근할 때 panic!을 호출하는 이유
    - 데이터 구조에 해당하지 않는 메모리에 접근하는 시도는 가장 일반적으로 발생
    - 특정 요구사항 만족할 때 그 동작을 보장하는 경우 panic! 호출시켜라
- 러스트의 타입시스템으로 인해 타입으로 보장되는 값은 테스트 안해도 됨

### 유효성 검사를 위한 커스텀 타입

- 유효성 검사를 위한 커스텀 타입 생성하는 방법
- 예시: 유효성 검사를 통해 1~100 사이 값이 아닐때 유도하거나 다른 동작을 수행할 수 있도록 개선한다.

```rust
loop {
  ...

  let guess: i32 = match guess.trim().parse() {
    Ok(num) => num,
    Err(_) => continue,
  };

  if guess < 1 || guess > 100 {
    println!("1에서 100 사이의 값을 입력해 주세요.");
    continue;
  }

  match guess.cmp(*secret_number);
  ...
}
```

- if 구문이 입력된 값 범위를 체크하고 사용자에게 입력값에 문제가 있음을 알린 후 continue 구문을 호출해서 사용자가 다시 값을 입력할 수 있도록 함

```rust
pub struct Guess {
  value: i32,
}

impl Guess {
  pub fn new(value: i32) -> Guess {
    if value < 1 || value > 100 {
      panic!("유추한 값은 반드시 1~100 사이 값이어야 함. 입력한 값:{}", value);
    }

    Guess {
      value
    }
  }

  pub fn value(&self) -> i32 {
    self.value
  }
}
```

- 캡슐화를 고려해서 구조를 작성한다.
  - value 필드의 값을 직접 조작하는 경우 방지
  - panic! 으로 하여금 더 명확하게 사용자가 알 수 있도록 제공한다.
- 이제 Guess::new 함수가 수행하는 조건 검사를 통과하지 않고 엉뚱한 값을 가진 Guess 타입은 절대 생성 불가하다

## 요약

- panic! 매크로는 프로그램이 제대로 처리할 수 없는 비정상적인 상태에 놓였다는 것을 알려줌 그리고 잘못된 값을 사용하지 못하도록 프로세스 종료함
- Result 열거자는 러스트의 타입 시스템을 이용해 작업이 실패할 수 있음을 명시, 실패한 경우 프로그램을 회복할 기회 제공
  - 성공, 실패 케이스 처리할 수 있도록 유도 가능
  - panic! 매크로와 Result 열거자를 적절하게 활용하면 좋음
